
---
# This playbook generates a snapshot for a VM managed by a vcenter server
- name: Generate VMware Snapshot
  hosts: localhost
  vars:
    # pass these in the environment or through Tower
    vcenter_server: your_vsphere_fqdn
    datacenter_name: your_vms_datacenter
    snap_name: snapshot_to_create
    inventory_name: your_inv_host_or_group
  
  tasks:  
  - name: Create a snapshot
    vmware_guest_snapshot:
      state: present
      # Weird how Tower requires the quotes and ansible does not...
      datacenter: '{{ datacenter_name }}'
      hostname: '{{ vcenter_server }}'
      name: '{{ item }}'
      snapshot_name: '{{ snap_name }}'
    with_inventory_hostnames:
    - '{{ inventory_name }}'
