---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: foreman_hostgroup_baserhel_testcpgpc
  remote_user: root

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
