---
# nginx in RHEL 7.5 SCL is at 1.12.1 
# only 2 minors behind stable community
# 20180926
# I have added additional notes here are these are examples.
# Normally I would let the plays be self documenting.
#
# NOTE: we really could specify restarted for our service module 
# at the end of this play. It is a trivial optimization in this 
# simple case if the the port was not enabled on the firewall
# but the configuration had not changed. Then we avoid a restart
# of the daemon. If the daemon took a long time to restart or 
# multple ports supporting active connections, this 
# might be useful. We are demonstrating functionality here.

# I prefer latest here vs. present as I control content
# versioning using Satellite
- name: Install nginx from Software Collections
  yum: 
    name: rh-nginx112-nginx
    state: latest

# Always rename your source templates with a .j2 
# extension. Its good form.
- name: Copy nginx configuration for wordpress
  template: 
    src: nginx.conf.j2 
    dest: /etc/opt/rh/rh-nginx112/nginx/nginx.conf
  notify: 
  - restart nginx

# See notes above
- name: Create firewalld rule for nginx
  firewalld: 
    port: "{{ nginx_port }}/tcp"
    permanent: true 
    state: enabled
    immediate: yes

- name: Start nginx http server
  service:
    name: rh-nginx112-nginx
    state: started
    enabled: yes

