---
# nginx in RHEL 7.5 is at 1.12.2 which is
# the latest we get on RHEL and only 2 minors behind stable community
# 20180926

- name: Install nginx
  yum: 
    name: nginx 
    state: latest

- name: Copy nginx configuration for wordpress
  template: 
    src: default.conf 
    dest: /etc/nginx/conf.d/default.conf
  notify: 
  - restart nginx

- name: Create firewalld rule for nginx
  firewalld: 
    port: "{{ nginx_port }}/tcp"
    permanent: true 
    state: enabled
    immediate: yes

- name: Start nginx http server
  service:
    name: nginx
    state: started
    enabled: yes

