---
# RHEL software collections provides nginx 1.12.1 
# using non-RHEL repos creates FrankenRHEL, so we won't
  
# Ditto for EPEL
# Only common component is to ensure that firewalld   
# is installed and started.
# BE CAREFUL ONLY port 22 is allowed by default

- name: Install Firewalld - this is default on RHEL7
  yum: 
    name: firewalld 
    state: latest
  
- name: Start Firewalld - this is default on RHEL7
  service: 
    name: firewalld 
    state: started 
    enabled: yes

